name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_push_auth:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Add registry to /etc/hosts
      run: echo "${{ secrets.SERVER_URL }} ${{ secrets.REGISTRY }}" | sudo tee -a /etc/hosts
    
    - name: Install CA certificate
      run: |
        sudo mkdir -p /etc/docker/certs.d/${{ secrets.REGISTRY }}:5000
        echo "${{ secrets.CA_CERT }}" | sudo tee /etc/docker/certs.d/${{ secrets.REGISTRY }}:5000/ca.crt
        sudo systemctl restart docker

    - name: Build and push wishlist-auth docker image
      uses: gacts/run-and-post-run@v1
      with:
        run: |
          VERSION=$(date +%s)
          docker build ./wishlist-auth --tag ${{ secrets.REGISTRY }}:5000/wishlist-auth:$VERSION
          docker tag ${{ secrets.REGISTRY }}:5000/wishlist-auth:$VERSION ${{ secrets.REGISTRY }}:5000/wishlist-auth:latest
          docker login -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_PASS }} ${{ secrets.REGISTRY }}:5000
          docker push --all-tags ${{ secrets.REGISTRY }}:5000/wishlist-auth
        post: |
          docker logout ${{ secrets.REGISTRY }}:5000

  build_and_push_discovery:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Add registry to /etc/hosts
      run: echo "${{ secrets.SERVER_URL }} ${{ secrets.REGISTRY }}" | sudo tee -a /etc/hosts

    - name: Install CA certificate
      run: |
        sudo mkdir -p /etc/docker/certs.d/${{ secrets.REGISTRY }}:5000
        echo "${{ secrets.CA_CERT }}" | sudo tee /etc/docker/certs.d/${{ secrets.REGISTRY }}:5000/ca.crt
        sudo systemctl restart docker

    - name: Build and push wishlist-discovery docker image
      uses: gacts/run-and-post-run@v1
      with:
        run: |
          VERSION=$(date +%s)
          docker build ./wishlist-discovery --tag ${{ secrets.REGISTRY }}:5000/wishlist-discovery:$VERSION
          docker tag ${{ secrets.REGISTRY }}:5000/wishlist-discovery:$VERSION ${{ secrets.REGISTRY }}:5000/wishlist-discovery:latest
          docker login -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_PASS }} ${{ secrets.REGISTRY }}:5000
          docker push --all-tags ${{ secrets.REGISTRY }}:5000/wishlist-discovery
        post: |
          docker logout ${{ secrets.REGISTRY }}:5000

  build_and_push_gateway:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Add registry to /etc/hosts
      run: echo "${{ secrets.SERVER_URL }} ${{ secrets.REGISTRY }}" | sudo tee -a /etc/hosts

    - name: Install CA certificate
      run: |
        sudo mkdir -p /etc/docker/certs.d/${{ secrets.REGISTRY }}:5000
        echo "${{ secrets.CA_CERT }}" | sudo tee /etc/docker/certs.d/${{ secrets.REGISTRY }}:5000/ca.crt
        sudo systemctl restart docker

    - name: Build and push wishlist-gateway docker image
      uses: gacts/run-and-post-run@v1
      with:
        run: |
          VERSION=$(date +%s)
          docker build ./wishlist-gateway --tag ${{ secrets.REGISTRY }}:5000/wishlist-gateway:$VERSION
          docker tag ${{ secrets.REGISTRY }}:5000/wishlist-gateway:$VERSION ${{ secrets.REGISTRY }}:5000/wishlist-gateway:latest
          docker login -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_PASS }} ${{ secrets.REGISTRY }}:5000
          docker push --all-tags ${{ secrets.REGISTRY }}:5000/wishlist-gateway
        post: |
          docker logout ${{ secrets.REGISTRY }}:5000

  build_and_push_wishlist:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Add registry to /etc/hosts
      run: echo "${{ secrets.SERVER_URL }} ${{ secrets.REGISTRY }}" | sudo tee -a /etc/hosts

    - name: Install CA certificate
      run: |
        sudo mkdir -p /etc/docker/certs.d/${{ secrets.REGISTRY }}:5000
        echo "${{ secrets.CA_CERT }}" | sudo tee /etc/docker/certs.d/${{ secrets.REGISTRY }}:5000/ca.crt
        sudo systemctl restart docker

    - name: Build and push wishlist docker image
      uses: gacts/run-and-post-run@v1
      with:
        run: |
          VERSION=$(date +%s)
          docker build ./wishlist --tag ${{ secrets.REGISTRY }}:5000/wishlist:$VERSION
          docker tag ${{ secrets.REGISTRY }}:5000/wishlist:$VERSION ${{ secrets.REGISTRY }}:5000/wishlist:latest
          docker login -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_PASS }} ${{ secrets.REGISTRY }}:5000
          docker push --all-tags ${{ secrets.REGISTRY }}:5000/wishlist
        post: |
          docker logout ${{ secrets.REGISTRY }}:5000

  deploy_to_server:
    needs: [build_and_push_auth, build_and_push_discovery, build_and_push_gateway, build_and_push_wishlist]
    runs-on: ubuntu-latest
    steps:
      - name: Pull and run latest wish app image
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_URL }}
          username: ${{ secrets.USER }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SERVER_PRIVATE_SSH_KEY }}
          script: |
            cd /app/wish/wishlist-backend
            docker login -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_PASS }} ${{ secrets.REGISTRY }}:5000
            docker compose pull
            docker compose up -d

      - name: Docker logout
        uses: gacts/run-and-post-run@v1
        with:
          post: docker logout ${{ secrets.REGISTRY }}:5000
